version: '3.8'

services:

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./envs/dev/.env
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  django:
    build:
      context: .
      dockerfile: ./docker/dev/django/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./envs/dev/.env
    depends_on:
      - db
      - redis
    working_dir: /usr/src/app

  bot_1h:
    build:
      context: .
      dockerfile: ./docker/dev/worker/Dockerfile
    command: python bot_1h.py
    volumes:
      - ./worker:/usr/src/worker
    env_file:
      - ./envs/dev/.env
    depends_on:
      - redis
    working_dir: /usr/src/worker

  bot_15m:
    build:
      context: .
      dockerfile: ./docker/dev/worker/Dockerfile
    command: python bot_15m.py
    volumes:
      - ./worker:/usr/src/worker
    env_file:
      - ./envs/dev/.env
    depends_on:
      - redis
    working_dir: /usr/src/worker

  bot_5m:
    build:
      context: .
      dockerfile: ./docker/dev/worker/Dockerfile
    command: python bot_5m.py
    volumes:
      - ./worker:/usr/src/worker
    env_file:
      - ./envs/dev/.env
    depends_on:
      - redis
    working_dir: /usr/src/worker

volumes:
  postgres_data:
